// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/vm.proto

package sreapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Virtualmachine struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Virtualmachine) Reset()         { *m = Virtualmachine{} }
func (m *Virtualmachine) String() string { return proto.CompactTextString(m) }
func (*Virtualmachine) ProtoMessage()    {}
func (*Virtualmachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{0}
}

func (m *Virtualmachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Virtualmachine.Unmarshal(m, b)
}
func (m *Virtualmachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Virtualmachine.Marshal(b, m, deterministic)
}
func (m *Virtualmachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Virtualmachine.Merge(m, src)
}
func (m *Virtualmachine) XXX_Size() int {
	return xxx_messageInfo_Virtualmachine.Size(m)
}
func (m *Virtualmachine) XXX_DiscardUnknown() {
	xxx_messageInfo_Virtualmachine.DiscardUnknown(m)
}

var xxx_messageInfo_Virtualmachine proto.InternalMessageInfo

func (m *Virtualmachine) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *Virtualmachine) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Virtualmachine) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Virtualmachine) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type ListRequest struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *ListRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ListRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type ListResponse struct {
	XApi                 string            `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Vms                  []*Virtualmachine `protobuf:"bytes,2,rep,name=vms,proto3" json:"vms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *ListResponse) GetVms() []*Virtualmachine {
	if m != nil {
		return m.Vms
	}
	return nil
}

type GetRequest struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *GetRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type GetResponse struct {
	XApi                 string          `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Vm                   *Virtualmachine `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *GetResponse) GetVm() *Virtualmachine {
	if m != nil {
		return m.Vm
	}
	return nil
}

type CreateRequest struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *CreateRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *CreateRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateResponse struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *CreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateRequest struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Newhostname          string   `protobuf:"bytes,5,opt,name=newhostname,proto3" json:"newhostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *UpdateRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *UpdateRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *UpdateRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateRequest) GetNewhostname() string {
	if m != nil {
		return m.Newhostname
	}
	return ""
}

type UpdateResponse struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *UpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteRequest struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *DeleteRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type DeleteResponse struct {
	XApi                 string   `protobuf:"bytes,1,opt,name=_api,json=Api,proto3" json:"_api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51142f146fd9438b, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetXApi() string {
	if m != nil {
		return m.XApi
	}
	return ""
}

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Virtualmachine)(nil), "sreapi.Virtualmachine")
	proto.RegisterType((*ListRequest)(nil), "sreapi.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "sreapi.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "sreapi.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "sreapi.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "sreapi.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "sreapi.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "sreapi.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "sreapi.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "sreapi.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "sreapi.DeleteResponse")
}

func init() { proto.RegisterFile("protobuf/vm.proto", fileDescriptor_51142f146fd9438b) }

var fileDescriptor_51142f146fd9438b = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0xec, 0x90, 0x96, 0x09, 0x29, 0xea, 0x96, 0xb6, 0xc6, 0x02, 0x11, 0xed, 0x01, 0xa2,
	0x48, 0x64, 0x45, 0xb8, 0x81, 0x40, 0x42, 0x20, 0x15, 0x89, 0x8f, 0x83, 0x25, 0x7a, 0x45, 0xdb,
	0x30, 0x6d, 0x8d, 0x6c, 0xef, 0xe2, 0xdd, 0x98, 0x43, 0x94, 0x0b, 0x3f, 0x80, 0x0b, 0x3f, 0x8d,
	0x2b, 0x47, 0x7e, 0x08, 0xf2, 0x3a, 0x5b, 0x7b, 0x51, 0x52, 0x81, 0x0f, 0xbd, 0xed, 0xcc, 0xee,
	0xbc, 0xf7, 0x66, 0xe6, 0xd9, 0xb0, 0x2b, 0x73, 0xa1, 0xc5, 0xc9, 0xfc, 0x94, 0x15, 0xe9, 0xc4,
	0x9c, 0x49, 0x4f, 0xe5, 0xc8, 0x65, 0x1c, 0xde, 0x39, 0x13, 0xe2, 0x2c, 0x41, 0xc6, 0x65, 0xcc,
	0x78, 0x96, 0x09, 0xcd, 0x75, 0x2c, 0x32, 0x55, 0xbd, 0xa2, 0x29, 0xec, 0x1c, 0xc7, 0xb9, 0x9e,
	0xf3, 0x24, 0xe5, 0xb3, 0xf3, 0x38, 0x43, 0xb2, 0x0b, 0xdd, 0x8f, 0x5c, 0xc6, 0x41, 0x67, 0xd8,
	0x19, 0x5d, 0x8f, 0xfc, 0x17, 0x32, 0x26, 0x21, 0x6c, 0x9f, 0x0b, 0xa5, 0x33, 0x9e, 0x62, 0xe0,
	0x99, 0xf4, 0x45, 0x4c, 0x02, 0xd8, 0x92, 0xb9, 0xf8, 0x8c, 0x33, 0x1d, 0xf8, 0xe6, 0xca, 0x86,
	0x84, 0x40, 0x37, 0x17, 0x09, 0x06, 0x5d, 0x93, 0x36, 0x67, 0xfa, 0x1e, 0xfa, 0x6f, 0x63, 0xa5,
	0x23, 0xfc, 0x32, 0x47, 0xa5, 0xd7, 0x71, 0x35, 0xf0, 0xbc, 0xf5, 0x78, 0x7e, 0x03, 0xef, 0x0d,
	0xdc, 0xa8, 0xf0, 0x94, 0x14, 0x99, 0x5a, 0x2b, 0x7e, 0x04, 0x7e, 0x91, 0xaa, 0xc0, 0x1b, 0xfa,
	0xa3, 0xfe, 0xf4, 0x60, 0x52, 0x4d, 0x65, 0xe2, 0x36, 0x1d, 0x95, 0x4f, 0xe8, 0x53, 0x80, 0x23,
	0xbc, 0x4c, 0xdb, 0x25, 0x73, 0xa0, 0xaf, 0xa1, 0x6f, 0x8a, 0x37, 0x0b, 0xb9, 0x0f, 0x5e, 0x91,
	0x9a, 0xba, 0xcd, 0x3a, 0xbc, 0x22, 0xa5, 0x09, 0x0c, 0x5e, 0xe6, 0xc8, 0x35, 0xb6, 0x53, 0xf2,
	0x9f, 0x1b, 0x79, 0x06, 0x3b, 0x96, 0x6d, 0xb3, 0xf4, 0x00, 0xb6, 0xd4, 0x7c, 0x36, 0x43, 0xa5,
	0x0c, 0xdb, 0x76, 0x64, 0x43, 0xfa, 0xbd, 0x03, 0x83, 0x0f, 0xf2, 0xd3, 0x15, 0xa9, 0x25, 0x43,
	0xe8, 0x67, 0xf8, 0xf5, 0x02, 0xec, 0x9a, 0xb9, 0x6a, 0xa6, 0xca, 0x7e, 0xac, 0x9e, 0x36, 0xfd,
	0x3c, 0x87, 0xc1, 0x2b, 0x4c, 0xb0, 0x6d, 0x3b, 0x25, 0xbd, 0xad, 0x6f, 0x41, 0x3f, 0xfd, 0xe5,
	0xc3, 0x4d, 0xd7, 0x12, 0x8a, 0x44, 0xd0, 0x2d, 0x3d, 0x4e, 0xf6, 0xac, 0x67, 0x1a, 0x5f, 0x50,
	0x78, 0xcb, 0x4d, 0x56, 0x9c, 0xf4, 0xde, 0xb7, 0x9f, 0xbf, 0x7f, 0x78, 0xb7, 0xc9, 0x21, 0x2b,
	0x1e, 0xb1, 0x22, 0x65, 0x8b, 0xd5, 0x4c, 0x97, 0x6c, 0x51, 0x8e, 0x71, 0x49, 0xde, 0x81, 0x7f,
	0x84, 0x9a, 0x10, 0x5b, 0x5d, 0xfb, 0x3e, 0xdc, 0x73, 0x72, 0x2b, 0xc0, 0xbb, 0x06, 0xf0, 0x90,
	0xec, 0xaf, 0x00, 0xc7, 0x6c, 0xcc, 0x16, 0xb6, 0xe9, 0x25, 0x39, 0x85, 0x5e, 0x65, 0x22, 0xb2,
	0x6f, 0xab, 0x1d, 0x0b, 0x87, 0x07, 0x7f, 0xa7, 0x57, 0xb8, 0x0f, 0x0d, 0xee, 0x03, 0x4a, 0x37,
	0x08, 0x6d, 0x90, 0x3c, 0xe9, 0x8c, 0x4b, 0x9e, 0x6a, 0xb9, 0x35, 0x8f, 0x63, 0xbe, 0x9a, 0xc7,
	0xf5, 0x80, 0xe5, 0x99, 0xfe, 0x23, 0xcf, 0x31, 0xf4, 0xaa, 0x2d, 0xd6, 0x3c, 0x8e, 0x2b, 0x6a,
	0x1e, 0x77, 0xd9, 0x76, 0x4e, 0xe3, 0xf5, 0x73, 0x3a, 0xe9, 0x99, 0x9f, 0xee, 0xe3, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x9e, 0xe6, 0x0c, 0xaf, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualmachinesClient is the client API for Virtualmachines service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualmachinesClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type virtualmachinesClient struct {
	cc *grpc.ClientConn
}

func NewVirtualmachinesClient(cc *grpc.ClientConn) VirtualmachinesClient {
	return &virtualmachinesClient{cc}
}

func (c *virtualmachinesClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/sreapi.Virtualmachines/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualmachinesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/sreapi.Virtualmachines/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualmachinesClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/sreapi.Virtualmachines/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualmachinesClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/sreapi.Virtualmachines/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualmachinesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/sreapi.Virtualmachines/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualmachinesServer is the server API for Virtualmachines service.
type VirtualmachinesServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterVirtualmachinesServer(s *grpc.Server, srv VirtualmachinesServer) {
	s.RegisterService(&_Virtualmachines_serviceDesc, srv)
}

func _Virtualmachines_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualmachinesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sreapi.Virtualmachines/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualmachinesServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtualmachines_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualmachinesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sreapi.Virtualmachines/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualmachinesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtualmachines_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualmachinesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sreapi.Virtualmachines/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualmachinesServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtualmachines_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualmachinesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sreapi.Virtualmachines/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualmachinesServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtualmachines_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualmachinesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sreapi.Virtualmachines/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualmachinesServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Virtualmachines_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sreapi.Virtualmachines",
	HandlerType: (*VirtualmachinesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Virtualmachines_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Virtualmachines_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Virtualmachines_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Virtualmachines_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Virtualmachines_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/vm.proto",
}
